zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    product-service:
      path: /product/**
      serviceId: template-product-service
    customer-service:
      path: /customer/**
      serviceId: template-customer-service
    order-service:
      path: /order/**
      serviceId: template-order-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.183.33:8761/isadco/tempAppEurekaService/eureka


server:
  port: 8079
  contextPath: /isadco/tempAppApiGateway
  

spring:
  application:
    name: template-api-gateway-service

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000